<a href="https://colab.research.google.com/github/KritishBokde91/NNDL_LAB/blob/main/NNDL_PRACTICAL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
#Vector Addition
vector1 = np.array([5, 10, 15])
vector2 = np.array([1, 8, 21])

result1 = vector1 + vector2
print(result1)

[ 6 18 36]


In [13]:
#Vector Multiplication
vector3 = np.array([[15, 30, 16], [25, 50, 27], [12, 18, 40]])
vector4 = np.array([[1, 16, 25], [88, 76, 4], [18, 36, 77]])

result2 = np.matmul(vector3, vector4)
print(result2)

[[2943 3096 1727]
 [4911 5172 2904]
 [2316 3000 3452]]
